### ISSUE TITLE
Error on application startup

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-nextxp#322]
When the Next.xp app starts on current snapshot of XP there's error in the logs. Since there's no longer default repository we should probably specify repository explicitly.

```
2024-05-22 10:08:40,932 ERROR c.e.xp.portal.impl.main.MainExecutor - Error while executing com.enonic.app.nextxp Application controller
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.enonic.xp.repository.RepositoryId.toString()" because the return value of "com.enonic.xp.context.Context.getRepositoryId()" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "com.enonic.xp.repository.RepositoryId.toString()" because the return value of "com.enonic.xp.context.Context.getRepositoryId()" is null
	at com.enonic.xp.lib.context.ContextMapper.serialize(ContextMapper.java:33)
	at com.enonic.xp.script.impl.util.JsObjectConverter.toJs(JsObjectConverter.java:63)
	at com.enonic.xp.script.impl.util.JsObjectConverter.toJs(JsObjectConverter.java:32)
	at com.enonic.xp.script.impl.function.ScriptFunctions.toNativeObject(ScriptFunctions.java:78)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$94$2208$context.L:1#get(com.enonic.app.nextxp:/lib/xp/context.js:63)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$93$3213$event.L:1#queryNextjsRepos(com.enonic.app.nextxp:/lib/nextxp/event.js:40)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$91$3067$event.L:1#subscribe(com.enonic.app.nextxp:/lib/nextxp/event.js:35)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$90$177$main.L:1#initialize(com.enonic.app.nextxp:/main.js:6)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$25$1AAAAAA$main.L:1(com.enonic.app.nextxp:/main.js:11)
	at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:678)
	at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
	at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:111)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.executeRequire(ScriptExecutorImpl.java:164)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.requireJs(ScriptExecutorImpl.java:216)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.requireJsOrJson(ScriptExecutorImpl.java:205)
	at com.enonic.xp.script.impl.executor.ScriptExportsCache.getOrCompute(ScriptExportsCache.java:53)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.executeRequire(ScriptExecutorImpl.java:135)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.doExecuteMain(ScriptExecutorImpl.java:118)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 4 common frames omitted
```

**Comment by alansemenov** [comment]
This is solved by rebuilding both the lib and the app with new XP version (current snapshot)
